# Generated by Django 4.0.4 on 2022-05-20 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_alter_payment_status_alter_shipment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Succeeded', 'Succeeded'), ('Failed', 'Failed'), ('Processing', 'Processing')], default='Processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Shipping', 'Shipping')], default='Pending', max_length=10),
        ),
    ]
