# Generated by Django 4.0.3 on 2022-04-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_id',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(
                choices=[('Returned', 'Returned'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'),
                         ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
