# Generated by Django 4.0.3 on 2022-03-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_author_item_create_at_item_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='Items',
        ),
    ]
