# Generated by Django 4.0.3 on 2022-03-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_product_sold_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
