# Generated by Django 4.0.3 on 2022-03-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='numbers_of_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Còn hàng'), ('H', 'Hết hàng'), ('CH', 'Chờ hàng')], max_length=2, null=True),
        ),
    ]
